# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ipinPro.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import PyQt5
if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
    PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
    PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(830, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(830, 600))
        MainWindow.setMaximumSize(QtCore.QSize(830, 600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowTitle("Ipin Pro 2019")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblEaName = QtWidgets.QLabel(self.centralwidget)
        self.lblEaName.setGeometry(QtCore.QRect(110, -10, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lblEaName.setFont(font)
        self.lblEaName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblEaName.setObjectName("lblEaName")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 260, 800, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(800, 300))
        self.tableWidget.setMaximumSize(QtCore.QSize(800, 300))
        self.tableWidget.setTabletTracking(True)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(18)
        self.tableWidget.verticalHeader().setDefaultSectionSize(18)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 230, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(550, 50, 261, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.slaveEquityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.slaveEquityLabel.setFont(font)
        self.slaveEquityLabel.setObjectName("slaveEquityLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.slaveEquityLabel)
        self.slaveEquity = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.slaveEquity.setFont(font)
        self.slaveEquity.setText("")
        self.slaveEquity.setFrame(False)
        self.slaveEquity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slaveEquity.setReadOnly(True)
        self.slaveEquity.setObjectName("slaveEquity")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.slaveEquity)
        self.slaveBalanceLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.slaveBalanceLabel.setFont(font)
        self.slaveBalanceLabel.setObjectName("slaveBalanceLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.slaveBalanceLabel)
        self.slaveBalance = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.slaveBalance.setFont(font)
        self.slaveBalance.setFrame(False)
        self.slaveBalance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slaveBalance.setReadOnly(True)
        self.slaveBalance.setObjectName("slaveBalance")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.slaveBalance)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.formLayoutWidget_2.setFont(font)
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(5, 5, 5, 5)
        self.formLayout_2.setSpacing(5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.masterLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.masterLabel.setFont(font)
        self.masterLabel.setObjectName("masterLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.masterLabel)
        self.lblBrokerAName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lblBrokerAName.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblBrokerAName.setFont(font)
        self.lblBrokerAName.setText("")
        self.lblBrokerAName.setFrame(False)
        self.lblBrokerAName.setReadOnly(True)
        self.lblBrokerAName.setObjectName("lblBrokerAName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblBrokerAName)
        self.slaveLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.slaveLabel.setFont(font)
        self.slaveLabel.setObjectName("slaveLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.slaveLabel)
        self.lblBrokerBName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lblBrokerBName.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblBrokerBName.setFont(font)
        self.lblBrokerBName.setFrame(False)
        self.lblBrokerBName.setReadOnly(True)
        self.lblBrokerBName.setObjectName("lblBrokerBName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblBrokerBName)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 120, 801, 91))
        self.horizontalLayoutWidget.setMinimumSize(QtCore.QSize(0, 60))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbTestExit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbTestExit.setMinimumSize(QtCore.QSize(0, 60))
        self.pbTestExit.setObjectName("pbTestExit")
        self.horizontalLayout.addWidget(self.pbTestExit)
        self.pbStop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbStop.setMinimumSize(QtCore.QSize(0, 60))
        self.pbStop.setObjectName("pbStop")
        self.horizontalLayout.addWidget(self.pbStop)
        self.pbRun = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbRun.setMinimumSize(QtCore.QSize(0, 60))
        self.pbRun.setObjectName("pbRun")
        self.horizontalLayout.addWidget(self.pbRun)
        self.pbTestClose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbTestClose.setMinimumSize(QtCore.QSize(0, 60))
        self.pbTestClose.setObjectName("pbTestClose")
        self.horizontalLayout.addWidget(self.pbTestClose)
        self.pbTestOpen = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbTestOpen.setMinimumSize(QtCore.QSize(0, 60))
        self.pbTestOpen.setObjectName("pbTestOpen")
        self.horizontalLayout.addWidget(self.pbTestOpen)
        self.pbReset = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbReset.setMinimumSize(QtCore.QSize(0, 60))
        self.pbReset.setObjectName("pbReset")
        self.horizontalLayout.addWidget(self.pbReset)
        self.pbDebug = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbDebug.setMinimumSize(QtCore.QSize(0, 60))
        self.pbDebug.setObjectName("pbDebug")
        self.horizontalLayout.addWidget(self.pbDebug)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDebug = QtWidgets.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSetting)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.lblEaName.setText(_translate("MainWindow", "Ipin Pro Expert Advisor"))
        self.tableWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>Gap 1 = Ask 1 - Bid 2</p><p>Gap2 = Ask 2 - Bid 1</p></body></html>"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ask A"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bid A"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ask B"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Bid B"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Gap UP"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Gap DOWN"))
        self.label.setText(_translate("MainWindow", "Market View"))
        self.slaveEquityLabel.setText(_translate("MainWindow", "Slave Equity"))
        self.slaveEquity.setPlaceholderText(_translate("MainWindow", "1,000,000.00"))
        self.slaveBalanceLabel.setText(_translate("MainWindow", "Slave Balance"))
        self.slaveBalance.setPlaceholderText(_translate("MainWindow", "1,000,000.00"))
        self.masterLabel.setText(_translate("MainWindow", "Master"))
        self.lblBrokerAName.setPlaceholderText(_translate("MainWindow", "Forex International Capital Market Group"))
        self.slaveLabel.setText(_translate("MainWindow", "Slave"))
        self.lblBrokerBName.setPlaceholderText(_translate("MainWindow", "Aisy Mikael Forex Solution Global Market"))
        self.pbTestExit.setText(_translate("MainWindow", "EXIT"))
        self.pbStop.setText(_translate("MainWindow", "STOP"))
        self.pbRun.setText(_translate("MainWindow", "RUN"))
        self.pbTestClose.setText(_translate("MainWindow", "CLOSE ALL"))
        self.pbTestOpen.setText(_translate("MainWindow", "OPEN ALL"))
        self.pbReset.setText(_translate("MainWindow", "RESET"))
        self.pbDebug.setText(_translate("MainWindow", "DEBUG"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDebug.setTitle(_translate("MainWindow", "Debug"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSetting.setText(_translate("MainWindow", "Setting"))

