# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting_rev2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingWindow(object):
    def setupUi(self, SettingWindow):
        SettingWindow.setObjectName("SettingWindow")
        SettingWindow.resize(774, 554)
        self.centralwidget = QtWidgets.QWidget(SettingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(680, 70, 81, 310))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbEurUsd = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbEurUsd.setFont(font)
        self.cbEurUsd.setObjectName("cbEurUsd")
        self.verticalLayout.addWidget(self.cbEurUsd)
        self.cbGbpUsd = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbGbpUsd.setFont(font)
        self.cbGbpUsd.setObjectName("cbGbpUsd")
        self.verticalLayout.addWidget(self.cbGbpUsd)
        self.cbAudUsd = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbAudUsd.setFont(font)
        self.cbAudUsd.setObjectName("cbAudUsd")
        self.verticalLayout.addWidget(self.cbAudUsd)
        self.cbNzdUsd = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbNzdUsd.setFont(font)
        self.cbNzdUsd.setObjectName("cbNzdUsd")
        self.verticalLayout.addWidget(self.cbNzdUsd)
        self.cbUsdJpy = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbUsdJpy.setFont(font)
        self.cbUsdJpy.setObjectName("cbUsdJpy")
        self.verticalLayout.addWidget(self.cbUsdJpy)
        self.cbUsdCad = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbUsdCad.setFont(font)
        self.cbUsdCad.setObjectName("cbUsdCad")
        self.verticalLayout.addWidget(self.cbUsdCad)
        self.cbUsdChf = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbUsdChf.setFont(font)
        self.cbUsdChf.setObjectName("cbUsdChf")
        self.verticalLayout.addWidget(self.cbUsdChf)
        self.cbEurJpy = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbEurJpy.setFont(font)
        self.cbEurJpy.setObjectName("cbEurJpy")
        self.verticalLayout.addWidget(self.cbEurJpy)
        self.cbGbpJpy = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbGbpJpy.setFont(font)
        self.cbGbpJpy.setObjectName("cbGbpJpy")
        self.verticalLayout.addWidget(self.cbGbpJpy)
        self.cbAudJpy = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbAudJpy.setFont(font)
        self.cbAudJpy.setObjectName("cbAudJpy")
        self.verticalLayout.addWidget(self.cbAudJpy)
        self.cbNzdJpy = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbNzdJpy.setFont(font)
        self.cbNzdJpy.setObjectName("cbNzdJpy")
        self.verticalLayout.addWidget(self.cbNzdJpy)
        self.cbCadJpy = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbCadJpy.setFont(font)
        self.cbCadJpy.setObjectName("cbCadJpy")
        self.verticalLayout.addWidget(self.cbCadJpy)
        self.cbChfJpy = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbChfJpy.setFont(font)
        self.cbChfJpy.setObjectName("cbChfJpy")
        self.verticalLayout.addWidget(self.cbChfJpy)
        self.cbEurGbp = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbEurGbp.setFont(font)
        self.cbEurGbp.setObjectName("cbEurGbp")
        self.verticalLayout.addWidget(self.cbEurGbp)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 70, 311, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.master_ip = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.master_ip.setFont(font)
        self.master_ip.setText("")
        self.master_ip.setObjectName("master_ip")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.master_ip)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.master_lot = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.master_lot.setFont(font)
        self.master_lot.setText("")
        self.master_lot.setObjectName("master_lot")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.master_lot)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.master_min_lot = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.master_min_lot.setFont(font)
        self.master_min_lot.setObjectName("master_min_lot")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.master_min_lot)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.master_slip = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.master_slip.setFont(font)
        self.master_slip.setObjectName("master_slip")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.master_slip)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.master_stopLoss = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.master_stopLoss.setFont(font)
        self.master_stopLoss.setText("")
        self.master_stopLoss.setObjectName("master_stopLoss")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.master_stopLoss)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.master_lot2usd = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.master_lot2usd.setFont(font)
        self.master_lot2usd.setObjectName("master_lot2usd")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.master_lot2usd)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.master_suffix = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.master_suffix.setFont(font)
        self.master_suffix.setObjectName("master_suffix")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.master_suffix)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 40, 119, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 290, 311, 211))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.slave_ip = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.slave_ip.setFont(font)
        self.slave_ip.setText("")
        self.slave_ip.setObjectName("slave_ip")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.slave_ip)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.slave_lot = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.slave_lot.setFont(font)
        self.slave_lot.setObjectName("slave_lot")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.slave_lot)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.slave_min_lot = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.slave_min_lot.setFont(font)
        self.slave_min_lot.setObjectName("slave_min_lot")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.slave_min_lot)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.slave_slip = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.slave_slip.setFont(font)
        self.slave_slip.setObjectName("slave_slip")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.slave_slip)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.slave_stoploss = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.slave_stoploss.setFont(font)
        self.slave_stoploss.setObjectName("slave_stoploss")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.slave_stoploss)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.slave_lot2usd = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.slave_lot2usd.setFont(font)
        self.slave_lot2usd.setObjectName("slave_lot2usd")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.slave_lot2usd)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.slave_suffix = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.slave_suffix.setFont(font)
        self.slave_suffix.setObjectName("slave_suffix")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.slave_suffix)
        self.takeProfitLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.takeProfitLabel.setFont(font)
        self.takeProfitLabel.setObjectName("takeProfitLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.takeProfitLabel)
        self.slave_takeprofit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.slave_takeprofit.setFont(font)
        self.slave_takeprofit.setObjectName("slave_takeprofit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.slave_takeprofit)
        self.orderCommentLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.orderCommentLabel.setFont(font)
        self.orderCommentLabel.setObjectName("orderCommentLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.orderCommentLabel)
        self.slave_comment = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.slave_comment.setFont(font)
        self.slave_comment.setObjectName("slave_comment")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.slave_comment)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(20, 40, 119, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(20, 260, 119, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(350, 40, 119, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(350, 70, 311, 241))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.magic_number = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.magic_number.setFont(font)
        self.magic_number.setText("")
        self.magic_number.setObjectName("magic_number")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.magic_number)
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.token = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.token.setFont(font)
        self.token.setObjectName("token")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.token)
        self.label_36 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.chat_id = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chat_id.setFont(font)
        self.chat_id.setObjectName("chat_id")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chat_id)
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.risk = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.risk.setFont(font)
        self.risk.setObjectName("risk")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.risk)
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.arb_open = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.arb_open.setFont(font)
        self.arb_open.setObjectName("arb_open")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.arb_open)
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.arb_close = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.arb_close.setFont(font)
        self.arb_close.setObjectName("arb_close")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.arb_close)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.pip_step = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pip_step.setFont(font)
        self.pip_step.setObjectName("pip_step")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pip_step)
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.scalping_rule = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scalping_rule.setFont(font)
        self.scalping_rule.setObjectName("scalping_rule")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.scalping_rule)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.next_open_duration = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.next_open_duration.setFont(font)
        self.next_open_duration.setObjectName("next_open_duration")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.next_open_duration)
        self.WeekendOff = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WeekendOff.setFont(font)
        self.WeekendOff.setObjectName("WeekendOff")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.WeekendOff)
        self.weekendOFFCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.weekendOFFCheckBox.setObjectName("weekendOFFCheckBox")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.weekendOFFCheckBox)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(350, 430, 411, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbSendTeleg = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbSendTeleg.setMinimumSize(QtCore.QSize(0, 60))
        self.pbSendTeleg.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pbSendTeleg.setFont(font)
        self.pbSendTeleg.setObjectName("pbSendTeleg")
        self.horizontalLayout_2.addWidget(self.pbSendTeleg)
        self.pbSave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbSave.setMinimumSize(QtCore.QSize(0, 60))
        self.pbSave.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pbSave.setFont(font)
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout_2.addWidget(self.pbSave)
        self.pbExit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbExit.setMinimumSize(QtCore.QSize(0, 60))
        self.pbExit.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pbExit.setFont(font)
        self.pbExit.setObjectName("pbExit")
        self.horizontalLayout_2.addWidget(self.pbExit)
        self.pbLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbLoad.setMinimumSize(QtCore.QSize(0, 60))
        self.pbLoad.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pbLoad.setFont(font)
        self.pbLoad.setObjectName("pbLoad")
        self.horizontalLayout_2.addWidget(self.pbLoad)
        SettingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 18))
        self.menubar.setObjectName("menubar")
        SettingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingWindow)
        self.statusbar.setObjectName("statusbar")
        SettingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SettingWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingWindow)

    def retranslateUi(self, SettingWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingWindow.setWindowTitle(_translate("SettingWindow", "Ipin Pro Setting"))
        self.label.setText(_translate("SettingWindow", "Setting"))
        self.cbEurUsd.setText(_translate("SettingWindow", "EURUSD"))
        self.cbGbpUsd.setText(_translate("SettingWindow", "GBPUSD"))
        self.cbAudUsd.setText(_translate("SettingWindow", "AUDUSD"))
        self.cbNzdUsd.setText(_translate("SettingWindow", "NZDUSD"))
        self.cbUsdJpy.setText(_translate("SettingWindow", "USDJPY"))
        self.cbUsdCad.setText(_translate("SettingWindow", "USDCAD"))
        self.cbUsdChf.setText(_translate("SettingWindow", "USDCHF"))
        self.cbEurJpy.setText(_translate("SettingWindow", "EURJPY"))
        self.cbGbpJpy.setText(_translate("SettingWindow", "GBPJPY"))
        self.cbAudJpy.setText(_translate("SettingWindow", "AUDJPY"))
        self.cbNzdJpy.setText(_translate("SettingWindow", "NZDJPY"))
        self.cbCadJpy.setText(_translate("SettingWindow", "CADJPY"))
        self.cbChfJpy.setText(_translate("SettingWindow", "CHFJPY"))
        self.cbEurGbp.setText(_translate("SettingWindow", "EURGBP"))
        self.label_2.setText(_translate("SettingWindow", "Master IP Address"))
        self.label_9.setText(_translate("SettingWindow", "Lot"))
        self.label_10.setText(_translate("SettingWindow", "Minimum Lot"))
        self.label_6.setText(_translate("SettingWindow", "Slippage"))
        self.label_13.setText(_translate("SettingWindow", "Stop Loss"))
        self.label_11.setText(_translate("SettingWindow", "Lot To USD Ratio"))
        self.label_14.setText(_translate("SettingWindow", "Master Symbol Suffix"))
        self.label_5.setText(_translate("SettingWindow", "Symbol"))
        self.label_8.setText(_translate("SettingWindow", "Slave IP Address"))
        self.label_22.setText(_translate("SettingWindow", "Lot"))
        self.label_24.setText(_translate("SettingWindow", "Minimum Lot"))
        self.label_23.setText(_translate("SettingWindow", "Slippage"))
        self.label_26.setText(_translate("SettingWindow", "Stop Loss"))
        self.label_25.setText(_translate("SettingWindow", "Lot To USD Ratio"))
        self.label_28.setText(_translate("SettingWindow", "Slave Symbol Suffix"))
        self.takeProfitLabel.setText(_translate("SettingWindow", "Take Profit"))
        self.orderCommentLabel.setText(_translate("SettingWindow", "Order Comment"))
        self.label_29.setText(_translate("SettingWindow", "Master"))
        self.label_30.setText(_translate("SettingWindow", "Slave"))
        self.label_31.setText(_translate("SettingWindow", "Common"))
        self.label_33.setText(_translate("SettingWindow", "Magic Number"))
        self.label_35.setText(_translate("SettingWindow", "Telegram Token   "))
        self.label_36.setText(_translate("SettingWindow", "Telegram Chat ID"))
        self.label_34.setText(_translate("SettingWindow", "Risk                    "))
        self.label_37.setText(_translate("SettingWindow", "Arbitrage Open"))
        self.label_38.setText(_translate("SettingWindow", "Arbitrage Close"))
        self.label_39.setText(_translate("SettingWindow", "Pip Step"))
        self.label_40.setText(_translate("SettingWindow", "Scalping Rule"))
        self.label_41.setText(_translate("SettingWindow", "Next Open Duration"))
        self.WeekendOff.setText(_translate("SettingWindow", "weekend OFF"))
        self.pbSendTeleg.setText(_translate("SettingWindow", "TELEGRAM"))
        self.pbSave.setText(_translate("SettingWindow", "SAVE"))
        self.pbExit.setText(_translate("SettingWindow", "EXIT"))
        self.pbLoad.setText(_translate("SettingWindow", "LOAD"))

